service: matcher

provider:
  name: aws
  runtime: python3.10
  region: eu-central-1
  memorySize: 256
  versionFunctions: false
  timeout: 30

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"

custom:
  wsgi:
    app: app.app
    pythonBin: python3
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
